name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 2.0.0
author: Sarbagya Dhaubanjar <sarbagyastha@gmail.com>
homepage: https://github.com/sarbagyastha/youtube_player_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ytview: 0.0.8-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter



