name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 4.0.0+2
author: Sarbagya Dhaubanjar <github@sarbagyastha.com.np>
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://sarbagyastha.com.np

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.11+2
  cached_network_image: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




