name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 5.0.1
author: Sarbagya Dhaubanjar <github@sarbagyastha.com.np>
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://sarbagyastha.com.np

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_connection_checker: ">=0.3.0 <1.0.0"
  webview_flutter: ">=0.3.15 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/speedometer.webp




