name:  Build and deploy
on:
  push:
    tags: 
      - '*'
jobs:
  build_deploy:
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
    name: Build apk
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: cd example && flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "example/build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
